### ISSUE TITLE
雷电模拟器闪退

### ISSUE THREAD

**Issue by wfrfred** [cwlm/SJTU_AutoRun#60]
**描述错误**
模拟器运行交我办 去跑步界面闪退；重启脚本后模拟器显示交我办屡次停止运行。

**复现步骤**
重现行为的步骤：
启动脚本

**期望行为**
对您期望发生的事情的描述。

**截图**
如果适用，请添加截图以帮助解释您的问题。

**附加内容**
目前预期解决方式 添加mumu模拟器备选项

**Comment by cwlm** [comment]
目前发现交我办3.4.3以上的版本会闪退

**Comment by wj0575** [comment]
在运行代码时，控制台持续出现如下反应，且定位没有发生变化，也无模拟gps信号，请问可能是出现了什么问题
[DEBUG 20:28:39 sjtuautorun] ('Emulator status', '')
ϵͳ�Ҳ���ָ����·����
ϵͳ�Ҳ���ָ����·����
ϵͳ�Ҳ���ָ����·����
ϵͳ�Ҳ���ָ����·����
[DEBUG 20:28:39 sjtuautorun] ('Emulator status', '')
ϵͳ�Ҳ���ָ����·����
[DEBUG 20:28:40 sjtuautorun] ('Emulator status', '')
ϵͳ�Ҳ���ָ����·����
[DEBUG 20:28:41 sjtuautorun] ('Emulator status', '')
ϵͳ�Ҳ���ָ����·����
[DEBUG 20:28:43 sjtuautorun] ('Emulator status', '')
ϵͳ�Ҳ���ָ����·����
[DEBUG 20:28:44 sjtuautorun] ('Emulator status', '')

**Comment by cwlm** [comment]
没找到模拟器，请新开一个issue

**Comment by fox-66666** [comment]
您好，我在操作至最后一步即运行start.py时报错，出现如下情况，由于是代码小白无法解决，麻烦作者大大帮忙一下
目前在前几步操作中暂未发现与说明不同的情况（截图上传失败故粘贴如下）
Traceback (most recent call last):
  File "D:\跑步\SJTU_AutoRun-main\SJTU_AutoRun-main\start.py", line 2, in <module>
    from sjtuautorun.scripts.main import start_script
  File "D:\跑步\SJTU_AutoRun-main\SJTU_AutoRun-main\sjtuautorun\scripts\main.py", line 11, in <module>
    from sjtuautorun.utils.update import check_for_updates
  File "D:\跑步\SJTU_AutoRun-main\SJTU_AutoRun-main\sjtuautorun\utils\update.py", line 7, in <module>
    import inquirer
  File "C:\Users\38464\AppData\Local\Programs\Python\Python311\Lib\site-packages\inquirer\__init__.py", line 1, in <module>
    from inquirer.prompt import prompt
  File "C:\Users\38464\AppData\Local\Programs\Python\Python311\Lib\site-packages\inquirer\prompt.py", line 1, in <module>
    import inquirer.themes as themes
  File "C:\Users\38464\AppData\Local\Programs\Python\Python311\Lib\site-packages\inquirer\themes.py", line 9, in <module>
    term = Terminal()
  File "C:\Users\38464\AppData\Local\Programs\Python\Python311\Lib\site-packages\blessed\terminal.py", line 164, in __init__
    self.__init__streams()
  File "C:\Users\38464\AppData\Local\Programs\Python\Python311\Lib\site-packages\blessed\terminal.py", line 253, in __init__streams
    self._init_descriptor = sys.__stdout__.fileno()
AttributeError: 'NoneType' object has no attribute 'fileno'
